### ISSUE TITLE
Isue with user login

### ISSUE THREAD

**Issue by Rashid941** [Abdullah-moiz/Job-Portal#5]
when user try to signup showing something went wrong please try again later

**Comment by Abdullah-moiz** [comment]
@Rashid941 i just tried it , working fine on my production application, If you are facing this issue in your localhost then its probably because of DB or environment variable issues ,do check it once if still didn't work then check the exact detail of the error in your console . hopefully you will understand. As response show message called something went wrong but it also logged error in console so you can track it
